image: jangrewe/gitlab-ci-android

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew

stages:
    - test
    - deploy

Validate MR:
  stage: test
  script:
    - ./gradlew cooee-android-sdk:test
    - ./gradlew cooee-android-sdk:publishToMavenLocal
  only:
    - merge_requests

Publish to JFrog:
    stage: deploy
    script:
      - ./gradlew clean cooee-android-sdk:artifactoryPublish -PartifactoryUser=${ARTIFACTORY_USER} -PartifactoryPassword=${ARTIFACTORY_PASS}
    only:
      - tags
    artifacts:
      paths:
        - cooee-android-sdk/build/outputs/aar

Publish to MavenCentral:
  stage: deploy
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/load-secure-files/-/raw/main/installer" | bash
    - ls
    - ls -lah .secure_files
    - ./gradlew cooee-android-sdk:publishReleasePublicationToSonatypeRepository -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSWORD} -PossrhUsername=${SONATYPE_USERNAME} -PossrhPassword=${SONATYPE_PASSWORD} -PsonatypeStagingProfileId=${SONATYPE_STAGING_PROFILE_ID} --stacktrace
  when: manual